noride/config/routes.rb
Rails.application.routes.draw do
  devise_for :developers, controllers: {
  sessions:      'developers/sessions',
  passwords:     'developers/passwords',
  registrations: 'developers/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  root to: 'top#index'
  get '/timeline' => 'top#timeline'
  get '/new' => 'top#new'
  get '/:userid', to: 'users#show_by_userid'

end

noride/app/controllers/top_controller.rb
class TopController < ApplicationController
  # skip_before_action :redirect_to_timeline, only: :index

  def index
  end

  def timeline
    @product = Product.all
  end

  def new
  end

  def show_by_userid
    @user = User.find_by!(userid: params[:userid])
    render :template => "users/show"
  end

  def show
    @user = User.find(params[:id])
  end


end

noride/app/helpers/top_helper.rb
module TopHelper
end

noride/app/views/top/index.html.erb
<div class="contents_wrap clearfix">
  <div class="left_contents">
    <nav>
      <ul>
        <% if user_signed_in? %>
        <li class="menu_lists"><%= link_to "Logout from User", destroy_user_session_path, method: :delete %></li>
        <% elsif developer_signed_in? %>
        <li class="menu_lists"><%= link_to "Logout from Developer", destroy_developer_session_path, method: :delete %></li>
        <% else %>
        <li class="menu_lists"><%= link_to "User Signup", "/users/sign_up" %></li>
        <li class="menu_lists"><%= link_to "Developer Signup", "/developers/sign_up" %></li>
        <li class="menu_lists"><%= link_to "User Login", "/users/sign_in" %></li>
        <li class="menu_lists"><%= link_to "Developer Login", "/developers/sign_in" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <div class="right_contents">
  <% if user_signed_in? %>
  <div class="each_rides_users">
    <p class="each_rides_title_users"></p>
  </div>
  <% elsif developer_signed_in? %>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride!!</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride i invented.</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride i invented.</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride i invented.</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride i invented.</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride i invented.</p>
  </div>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">My ride</p>
  </div>
  <% else %>
  <div class="not_login_view">
    <h3 class="not_login_view_title">This is Noride Website.</h3>
    <section class="not_login_view_contents">
      <p><%= image_tag 'riding_photo.jpg' %></p>
      <p>世界は変わっています。日々暮らしのあり方、食べ物に対する概念。</p>
      <p>次は乗り物のあり方が変わるべきです。日常の中で移動時間というものは非常に「無駄」であると考えられます。</p>
      <p>その無駄な時間をNorideは有意義な時間へと変貌させるべく始動した新たな暮らしのスタイルを求めるチームです。</p>
    </section>
    <h3 class="not_login_view_title">Why I built this.</h3>
    <p></p>
  </div>
  <% end %>
</div>
</div>

noride/app/views/top/new.html.erb
<div class="contents row">
  <%= form_tag('/tweets', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <input placeholder="Nickname" type="text" name="name">
    <input placeholder="Image Url" type="text" name="image">
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div><div class="contents row">
  <%= form_tag('/tweets', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <input placeholder="Nickname" type="text" name="name">
    <input placeholder="Image Url" type="text" name="image">
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

noride/app/views/top/search.html.erb
<div class='content'>
  <div id="search-box">
    <%= form_tag('/', method: :get) do %>
        <%= text_field_tag :book, "",  id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%><button title="検索" type="submit">検索</button>
    <% end %>
  </div>
  <h2>検索結果</h2>
  <div id='book_list'>
   <%= render partial: 'book_list' %>
  </div>
</div>

noride/app/views/top/timeline.html.erb
<div class="contents_wrap clearfix">
  <div class="left_contents">
    <nav>
      <ul>
        <% if user_signed_in? %>
        <li class="menu_lists"><%= link_to "Logout from User", destroy_user_session_path, method: :delete %></li>
        <% elsif developer_signed_in? %>
        <li class="menu_lists"><%= link_to "Logout from Developer", destroy_developer_session_path, method: :delete %></li>
        <% else %>
        <li class="menu_lists"><%= link_to "User Signup", "/users/sign_up" %></li>
        <li class="menu_lists"><%= link_to "Developer Signup", "/developers/sign_up" %></li>
        <li class="menu_lists"><%= link_to "User Login", "/users/sign_in" %></li>
        <li class="menu_lists"><%= link_to "Developer Login", "/developers/sign_in" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <div class="right_contents">
  <% if user_signed_in? %>
  <div class="each_rides_users">
    <p class="each_rides_title_users">
      <% @product.each do |product| %>
    <p><%= product.image %></p>
    <p><%= product.ride_name %></p>
    <p><%= product.nickname %></p>
    <p><%= product.price %></p>
    <p><%= product.concept %></p>
    </p>
    <% end %>
  </div>
  <% elsif developer_signed_in? %>
  <div class="each_rides_devs">
    <p class="each_rides_title_devs">テストです。</p>
  </div>
  <% else %>
  <div class="not_login_view">
    <h3 class="not_login_view_title">This is Noride Website.</h3>
    <section class="not_login_view_contents">
      <p><%= image_tag 'riding_photo.jpg' %></p>
      <p>世界は変わっています。日々暮らしのあり方、食べ物に対する概念。</p>
      <p>次は乗り物のあり方が変わるべきです。日常の中で移動時間というものは非常に「無駄」であると考えられます。</p>
      <p>その無駄な時間をNorideは有意義な時間へと変貌させるべく始動した新たな暮らしのスタイルを求めるチームです。</p>
    </section>
    <h3 class="not_login_view_title">Why I built this.</h3>
    <p></p>
  </div>
  <% end %>
</div>
</div>